<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FaqSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $faqs = [
            [
                'question' => 'Koji su navažniji nutrijenti u našoj ishrani?',
                'answer' => 'Najvažniji nutrijenti u našoj ishrani su: proteini, ugljeni hidrati, masti, vitamini, minerali i voda. Svi ovi nutrijenti su neophodni za pravilno funkcionisanje organizma i održavanje zdrave ravnoteže u telu.',
                'html_answer' => '<p>Najvažniji nutrijenti u našoj ishrani su:</p><ul><li>proteini</li><li>ugljeni hidrati</li><li>masti</li><li>vitamini</li><li>minerali</li><li>voda</li></ul><p>Svi ovi nutrijenti su neophodni za pravilno funkcionisanje organizma i održavanje zdrave ravnoteže u telu.</p>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice su najbogatije proteinima?',
                'answer' => 'Namirnice koje su najbogatije proteinima su: meso (posebno crveno meso, piletina, ćuretina, riba), mleko i mlečni proizvodi, jaja, soja (tofu sir), pasulj i druge mahunarke. Ove namirnice su izvor kvalitetnih proteina, koji su neophodni za izgradnju i održavanje tkiva u organizmu.',
                'html_answer' => '<p>Namirnice koje su najbogatije proteinima su:</p><ul><li>meso (posebno crveno meso, piletina, ćuretina, riba)</li><li>mleko i mlečni proizvodi</li><li>jaja</li><li>soja (tofu sir)</li><li>pasulj i druge mahunarke</li></ul><p>Ove namirnice su izvor kvalitetnih proteina, koji su neophodni za izgradnju i održavanje tkiva u organizmu.</p>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice su najbogatije zdravim ugljenim hidratima?',
                'answer' => 'Namirnice koje su najbogatije ugljenim hidratima su: šećerni škrobni proizvodi (hleb, testenina, krompir, pirinač), voće (posebno banana i grožđe), med, urme, suvo voće, pahuljice. Takođe, integralne žitarice, voće i povrće daju duži, stabilniji izvor energije.',
                'html_answer' => '<p>Namirnice koje su najbogatije ugljenim hidratima su:</p><ul><li>šećerni škrobni proizvodi (hleb, testenina, krompir, pirinač)</li><li>voće (posebno banana i grožđe)</li><li>med</li><li>urme</li><li>suvo voće</li><li>pahuljice</li></ul><p>Takođe, integralne žitarice, voće i povrće daju duži, stabilniji izvor energije.</p>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice su najbogatije zdravim mastima?',
                'answer' => 'Namirnice koje su najbogatije zdravim mastima su: maslinovo ulje, avokado, orašasti plodovi, semenke, losos i druge vrste ribe, puter od kikirikija, susam i tan.',
                'html_answer' => '<p>Namirnice koje su najbogatije zdravim mastima su:</p><ul><li>maslinovo ulje</li><li>avokado</li><li>orašasti plodovi</li><li>semenke</li><li>losos i druge vrste ribe</li><li>puter od kikirikija</li><li>susam i tan</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice su najbogatije vlaknima?',
                'answer' => 'Namirnice koje su najbogatije vlaknima su: povrće, voće sa “kožom”, integralne žitarice, mahunarke, čia i lanene semenke.',
                'html_answer' => '<p>Namirnice koje su najbogatije vlaknima su:</p><ul><li>povrće</li><li>voće sa “kožom”</li><li>integralne žitarice</li><li>mahunarke</li><li>čia i lanene semenke</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice su najbogatije vitaminima i mineralima?',
                'answer' => 'Namirnice koje su najbogatije vitaminima i mineralima su: crveno meso, riba i morski plodovi, raznovrsno voće i povrće, koštunjavo voće, semenke, integralne žitarice.',
                'html_answer' => '<p>Namirnice koje su najbogatije vitaminima i mineralima su:</p><ul><li>crveno meso</li><li>riba i morski plodovi</li><li>raznovrsno voće i povrće</li><li>koštunjavo voće</li><li>semenke</li><li>integralne žitarice</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koliko proteina dnevno treba da unosimo?',
                'answer' => 'Dnevne potrebe za proteinima kod sedentarnih ljudi su oko 1g po kg telesne mase, a kod fizički aktivnih osoba od 1.6 do 2.2g po kg.',
                'html_answer' => '<p>Dnevne potrebe za proteinima:</p><ul><li>sedentarni ljudi: oko 1g/kg</li><li>aktivni ljudi: 1.6–2.2g/kg</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koliko ugljenih hidrata dnevno treba da unosimo?',
                'answer' => 'Unos ugljenih hidrata zavisi od fizičke aktivnosti. Prosečno: 100 do 150g dnevno.',
                'html_answer' => '<p>Prosečan dnevni unos ugljenih hidrata:</p><ul><li>100–150g</li><li>više za aktivne osobe</li><li>manje za manje aktivne</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koliko masti dnevno treba da unosimo?',
                'answer' => 'Dnevni unos masti treba da bude oko 1g po kilogramu telesne mase, zavisi od fizičke aktivnosti. Važno je unositi zdrave masti, a izbegavati trans masti.',
                'html_answer' => '<p>Dnevni unos masti:</p><ul><li>oko 1g/kg</li><li>unos zavisi od aktivnosti</li><li>fokus na zdrave masti</li><li>izbegavati trans masti</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Šta su zdrave masti a koje treba da izbegavamo?',
                'answer' => 'Zdrave masti su nezasićene masne kiseline iz avokada, orašastih plodova, maslinovog ulja i ribe. Nezdrave masti su zasićene i trans masti iz prerađenog mesa, margarina i pržene hrane.',
                'html_answer' => '<p>Zdrave masti:</p><ul><li>avokado</li><li>orašasti plodovi</li><li>maslinovo ulje</li><li>riba</li></ul><p>Nezdrave masti:</p><ul><li>prerađeno meso</li><li>margarin</li><li>pržena hrana</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koju hranu treba izbegavati kada hoćemo da smršamo?',
                'answer' => 'Treba izbegavati hranu bogatu rafinisanim šećerima, nezdravim mastima i soli. To uključuje brzu hranu, čips, gazirane napitke, čokoladice, peciva i hranu sa industrijskim uljima.',
                'html_answer' => '<p>Izbegavati sledeće:</p><ul><li>brzu hranu</li><li>čips</li><li>gazirane napitke</li><li>čokoladice</li><li>peciva</li><li>industrijska ulja</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Da li su sve vrste povrća dobre za nas?',
                'answer' => 'Sve vrste povrća su korisne, ali neke su bogatije nutrijentima. Najzdraviji su neprerađeni oblici, posebno zeleno lisnato povrće.',
                'html_answer' => '<p>Najzdravije povrće:</p><ul><li>zeleno lisnato (zelena salata, spanać, krastavac)</li><li>neprerađeno povrće</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Da li su sve vrste voća dobre za nas?',
                'answer' => 'Uglavnom da. Voće sadrži vitamine, minerale i vlakna, ali neka vrsta ima više šećera i treba ih konzumirati umerenije ako se prati dijeta.',
                'html_answer' => '<p>Voće je zdravo, ali:</p><ul><li>neke vrste imaju više šećera</li><li>umeren unos kod dijete sa ograničenjem šećera</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Da li je meso dobro za nas?',
                'answer' => 'Meso je izvor proteina i važnih nutrijenata poput gvožđa i B12, ali treba ga konzumirati umerenije zbog životinjskih masti i holesterola.',
                'html_answer' => '<p>Prednosti mesa:</p><ul><li>izvor proteina</li><li>sadrži gvožđe i B12</li></ul><p>Preporuka:</p><ul><li>umerena konzumacija</li><li>alternativa: pasulj, mahunarke</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Da li su mlečni proizvodi dobri za nas?',
                'answer' => 'Mlečni proizvodi su dobar izvor kalcijuma, proteina i vitamina D, ali neki ljudi imaju intoleranciju na laktozu. Potrebno je prilagoditi unos individualnim potrebama.',
                'html_answer' => '<p>Prednosti mlečnih proizvoda:</p><ul><li>kalcijum</li><li>protein</li><li>vitamin D</li></ul><p>Napomena:</p><ul><li>intolerancija na laktozu kod pojedinaca</li><li>koristiti biljne alternative ako je potrebno</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje su najbolje namirnice za održavanje energije tokom dana?',
                'answer' => 'Za energiju tokom dana preporučuju se složeni ugljeni hidrati, proteini i zdrave masti. Voće, povrće, integralne žitarice, nemasno meso i voda su ključni.',
                'html_answer' => '<p>Najbolje za energiju:</p><ul><li>voće i povrće</li><li>integralne žitarice</li><li>nemasni proteini</li><li>zdrave masti</li><li>dovoljno vode</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice je najbolje jesti za doručak?',
                'answer' => 'Doručak treba da sadrži proteine, ugljene hidrate i masti. Preporučuju se jaja, mlečni proizvodi, kvalitetne mesne prerađevine, hleb, orašasti plodovi i sveže povrće.',
                'html_answer' => '<p>Za doručak:</p><ul><li>jaja</li><li>mlečni proizvodi</li><li>nemasno meso</li><li>hleb/tost</li><li>orašasti plodovi</li><li>sveže povrće</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice je najbolje jesti za ručak?',
                'answer' => 'Ručak treba da bude uravnotežen i da sadrži proteine, ugljene hidrate, zdrave masti, povrće i voće. Preporučuju se jela od povrća i mesa, salate, ovsena kaša sa orašastim plodovima.',
                'html_answer' => '<p>Primeri zdravog ručka:</p><ul><li>jela od povrća i mesa</li><li>salate</li><li>sendviči sa piletinom i avokadom</li><li>ovsena kaša sa orašastim plodovima</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice je najbolje jesti za večeru?',
                'answer' => 'Za večeru su preporučene namirnice sa niskim glikemijskim indeksom, koje sadrže proteine i kompleksne ugljene hidrate: povrće, meso, riba, integralne žitarice, mahunarke.',
                'html_answer' => '<p>Preporučene večere:</p><ul><li>povrće</li><li>meso</li><li>riba</li><li>integralne žitarice</li><li>mahunarke</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje namirnice je najbolje jesti za užinu?',
                'answer' => 'Za užinu se preporučuju jednostavne i zdrave opcije: voće, koštunjavo voće, jogurt, celer, integralni hleb sa humusom, nemasno meso.',
                'html_answer' => '<p>Zdrave užine:</p><ul><li>voće</li><li>koštunjavo voće</li><li>jogurt</li><li>celer</li><li>integralni hleb sa humusom</li><li>nemasno meso</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako da se hranimo zdravo, bez da potrošimo mnogo novca?',
                'answer' => 'Kupujte sezonsko povrće i voće, kupujte u većim količinama, izbegavajte prerađene proizvode i kuvajte kod kuće. To štedi novac i povećava nutritivni kvalitet obroka.',
                'html_answer' => '<p>Saveti za zdravu i jeftinu ishranu:</p><ul><li>kupujte sezonsko voće i povrće</li><li>kupujte u većim količinama</li><li>izbegavajte prerađene proizvode</li><li>kuvajte kod kuće</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako da povećamo unos proteina u toku dana?',
                'answer' => 'Jedite više proteinskih namirnica (meso, riba, jaja, mlečni proizvodi, tofu, mahunarke), pijte proteinske napitke, dodajte proteinski prah u obroke i jedite češće manje obroke.',
                'html_answer' => '<p>Načini za veći unos proteina:</p><ul><li>više mesa, jaja, ribe, mlečnih proizvoda</li><li>proteinski šejkovi</li><li>proteinski prah u smutijima i obrocima</li><li>manji, češći obroci bogati proteinima</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako da povećamo unos ugljenih hidrata u toku dana?',
                'answer' => 'Jedi više žitarica, više voća sa visokim sadržajem ugljenih hidrata (banane, grožđe), prave šejkove sa voćem i medom, uz pažnju na ravnotežu i izbegavanje previše šećera.',
                'html_answer' => '<p>Unos ugljenih hidrata:</p><ul><li>žitarice (hleb, pahuljice, testenina, pirinač)</li><li>voće bogato ugljenim hidratima</li><li>voćni šejkovi sa medom</li><li>umeren unos šećera</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako da povećamo unos zdravih masti u toku dana?',
                'answer' => 'Dodajte maslinovo ulje u salate, jedite avokado, ribu bogatu omega-3, orašaste plodove, semenke, i koristite putere od orašastih plodova.',
                'html_answer' => '<p>Zdrave masti uključuju:</p><ul><li>maslinovo ulje</li><li>avokado</li><li>riba (losos, sardine)</li><li>orašasti plodovi</li><li>laneno, konopljino i čia seme</li><li>puteri od orašastih plodova</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako da povećamo unos vlakana u toku dana?',
                'answer' => 'Jedite više integralnih žitarica, voća i povrća, mahunarki, orašastih plodova i semenki. Postepeno povećavajte unos vlakana da izbegnete probavne smetnje.',
                'html_answer' => '<p>Načini za više vlakana:</p><ul><li>integralne žitarice</li><li>voće i povrće</li><li>mahunarke</li><li>orašasti plodovi i semenke</li><li>izbegavati prerađene namirnice</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje su najbolje namirnice za zdravlje srca?',
                'answer' => 'Najbolje su one sa malo trans masti i šećera, a puno vlakana, vitamina i omega-3: povrće, voće, riba, maslinovo ulje, orasi, integralne žitarice.',
                'html_answer' => '<p>Preporučene za zdravlje srca:</p><ul><li>povrće (kupus, brokoli, šargarepa)</li><li>voće (jagode, borovnice)</li><li>omega-3 (riba, laneno seme)</li><li>maslinovo ulje</li><li>integralne žitarice</li><li>orah i semenke</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje su najbolje namirnice za zdravlje mozga?',
                'answer' => 'Najbolje su one bogate omega-3 masnim kiselinama, antioksidansima i vitaminima: riba, avokado, maslinovo ulje, orasi, borovnice, šargarepa.',
                'html_answer' => '<p>Namirnice za mozak:</p><ul><li>omega-3 (riba, laneno ulje)</li><li>avokado, maslinovo ulje</li><li>orasi i semenke</li><li>borovnice, tamno lisnato povrće</li><li>integralne žitarice</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje su najbolje namirnice za zdravu kožu?',
                'answer' => 'Za zdravu kožu važni su antioksidansi, omega-3, vitamini A, C, E, cink i selen: jagode, spanać, paprika, orasi, losos, jogurt.',
                'html_answer' => '<p>Preporučene namirnice:</p><ul><li>voće i povrće (jagode, brokoli, paprika)</li><li>riba i omega-3</li><li>orašasti plodovi i semenke</li><li>proteini (jogurt, tofu)</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje su najbolje namirnice za zdravlje kostiju?',
                'answer' => 'Potrebne su namirnice bogate kalcijumom, magnezijumom, vitaminom D i fosforom: mlečni proizvodi, mahunarke, brokoli, riba, orašasti plodovi.',
                'html_answer' => '<p>Preporučene za kosti:</p><ul><li>mleko, jogurt, sir</li><li>mahunarke</li><li>povrće (brokoli, kelj)</li><li>riba (losos, sardine)</li><li>orašasti plodovi</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje su najbolje namirnice za zdravlje očiju?',
                'answer' => 'Za zdravlje očiju važne su namirnice bogate vitaminima A, C, E, luteinom i omega-3: šargarepa, brokoli, kivi, losos, semenke, mahunarke.',
                'html_answer' => '<p>Hrana za oči:</p><ul><li>voće i povrće (šargarepa, kivi, paprika)</li><li>riba bogata omega-3</li><li>zeleno lisnato povrće</li><li>orašasti plodovi i semenke</li><li>mahunarke</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje su najbolje namirnice za zdravlje želuca?',
                'answer' => 'Najbolje namirnice za želudac su: povrće (kupus, cvekla, brokoli), voće (jabuke, kruške), integralne žitarice, fermentisani proizvodi, omega-3 masti, probiotici i nemasni proteini.',
                'html_answer' => '<p>Preporučene za želudac:</p><ul><li>kupus, cvekla, brokoli</li><li>jabuke, kruške</li><li>integralne žitarice</li><li>kefir, jogurt, kiselo mleko</li><li>losos, avokado</li><li>probiotici</li><li>piletina, tofu</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koje su najbolje namirnice za dobar imunitet?',
                'answer' => 'Za jak imunitet preporučuju se: voće i povrće bogato vitaminima C, A i E, proteini (meso, riba, jaja, tofu), omega-3 masti, probiotici i biljni čajevi.',
                'html_answer' => '<p>Za jačanje imuniteta:</p><ul><li>voće i povrće (pomorandža, kivi, šargarepa)</li><li>proteini (meso, jaja, tofu)</li><li>omega-3 masti (riba, orasi)</li><li>probiotici (jogurt, kiseli kupus)</li><li>zeleni i crni čaj</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako nam se menja ishrana dok starimo?',
                'answer' => 'Stariji ljudi imaju manju potrebu za kalorijama, veću za proteinima, kalcijumom i vitaminom D. Potrebno je prilagoditi ishranu lakšim obrocima i češćim unosom nutrijenata.',
                'html_answer' => '<p>Promene u ishrani sa godinama:</p><ul><li>smanjen unos kalorija</li><li>veći unos proteina i vitamina D</li><li>češći i manji obroci</li><li>lakša hrana za varenje</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako vežbanje utiče na našu ishranu?',
                'answer' => 'Vežbanje povećava potrebe za kalorijama, proteinima i tečnošću. Važno je unositi dovoljno energije i nutrijenata da bi se postigli ciljevi i izbegla iscrpljenost.',
                'html_answer' => '<p>Uticaj vežbanja:</p><ul><li>veći unos kalorija i proteina</li><li>važno je unositi dovoljno vode</li><li>vežbanje podstiče zdravu ishranu</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako trudnoća utiče na našu ishranu?',
                'answer' => 'Tokom trudnoće raste potreba za proteinima, gvožđem, kalcijumom, omega-3 i vitaminima. Treba izbegavati sirove proizvode i alkohol, a povećati unos zdravih nutrijenata.',
                'html_answer' => '<p>Prehrana u trudnoći:</p><ul><li>više proteina, gvožđa, kalcijuma, omega-3</li><li>izbegavati sirove proizvode i alkohol</li><li>raznovrsna ishrana je ključna</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako dojenje utiče na našu ishranu?',
                'answer' => 'Dojenje povećava energetske i nutritivne potrebe žene. Potrebno je više tečnosti, proteina i zdravih masti. Ishrana treba biti uravnotežena i raznovrsna.',
                'html_answer' => '<p>Preporuke tokom dojenja:</p><ul><li>veći unos tečnosti</li><li>povećan unos proteina i masti</li><li>izbalansirana i bogata ishrana</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koliko vode dnevno treba da unosimo?',
                'answer' => 'Preporučeno je oko 2 litra dnevno za odrasle. Potrebe rastu kod fizičke aktivnosti, vrućine i tokom trudnoće ili dojenja.',
                'html_answer' => '<p>Preporučeni unos vode:</p><ul><li>2 litra za odrasle</li><li>više ako vežbate ili je toplo</li><li>trudnice i dojilje treba da unose više</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako unos vode utiče na našu ishranu?',
                'answer' => 'Voda je ključna za funkcionisanje organa, transport hranljivih materija i regulaciju temperature. Nedostatak vode može izazvati umor i dehidraciju.',
                'html_answer' => '<p>Uloga vode u organizmu:</p><ul><li>transport hranljivih materija</li><li>regulacija temperature</li><li>izbacivanje toksina</li><li>prevencija dehidracije</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako se hraniti kada imamo malo slobodnog vremena?',
                'answer' => 'Planirajte obroke unapred, nosite zdrave užine, kuvajte kod kuće kada možete i birajte zdrave opcije kad jedete van kuće.',
                'html_answer' => '<p>Saveti:</p><ul><li>planirajte obroke</li><li>nosite zdrave užine</li><li>kuvajte kad možete</li><li>birajte zdravu brzu hranu (npr. salate)</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako se hraniti kada smo van kuće ili putujemo?',
                'answer' => 'Pripremite užine unapred, birajte zdrave opcije u restoranima, pijte dovoljno vode i jedite redovno.',
                'html_answer' => '<p>Preporuke za ishranu u pokretu:</p><ul><li>ponesite voće, orašaste plodove, jogurt</li><li>birajte zdrave obroke u restoranima</li><li>pijte vodu redovno</li><li>izbegavajte prekomeran unos soli i šećera</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako pakovati hranu, da zadrži svoju nutritivnu vrednost?',
                'answer' => 'Hranu treba pakovati u vakuum kesice ili staklene posude, čuvati u frižideru, zaštititi od svetlosti i održavati odgovarajuću temperaturu.',
                'html_answer' => '<p>Saveti za pakovanje hrane:</p><ul><li>vakuumsko pakovanje</li><li>staklene posude</li><li>hladno i tamno mesto</li><li>održavanje preporučene temperature</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako ispravno čitati opis hrane i nutritivne vrednosti?',
                'answer' => 'Obratite pažnju na veličinu porcije, kalorije, makronutrijente, mikronutrijente i prisustvo aditiva ili dodanih šećera.',
                'html_answer' => '<p>Na šta obratiti pažnju:</p><ul><li>veličina porcije</li><li>kalorije</li><li>makro i mikronutrijenti</li><li>dodati šećeri i aditivi</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako koristiti suplemente i koje?',
                'answer' => 'Suplementi poput vitamina C, D, kalcijuma, omega-3 i probiotika mogu pomoći ako postoji manjak. Uzimajte ih po savetu lekara.',
                'html_answer' => '<p>Uobičajeni suplementi:</p><ul><li>vitamin C, D</li><li>kalcijum</li><li>omega-3 masne kiseline</li><li>probiotici</li><li>magnezijum</li></ul><p>Uzimati po preporuci stručnjaka.</p>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako ne prekršiti dijetu?',
                'answer' => 'Planirajte obroke, zamenite omiljene grickalice zdravijim opcijama, vodite dnevnik ishrane, pijte vodu i vežbajte redovno.',
                'html_answer' => '<p>Saveti za održavanje dijete:</p><ul><li>planiranje obroka</li><li>zdrave zamene</li><li>vođenje dnevnika</li><li>dovoljno sna i vode</li><li>fizička aktivnost</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Šta uraditi u slučaju prekršene dijete?',
                'answer' => 'Ne krivite sebe, nastavite sledeći dan kao planirano, analizirajte uzrok i fokusirajte se na uspehe i rutinu.',
                'html_answer' => '<p>Ako prekršite dijetu:</p><ul><li>ne okrivljujte sebe</li><li>nastavite sledeći dan</li><li>fokus na dobre navike</li><li>potražite podršku ako treba</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Koji su najčešći poremećaji u ishrani i kako ih tretirati?',
                'answer' => 'Najčešći su anoreksija, bulimija, binge eating i ortoreksija. Leče se terapijom, podrškom i zdravom ishranom.',
                'html_answer' => '<p>Poremećaji u ishrani:</p><ul><li>anoreksija</li><li>bulimija</li><li>binge eating</li><li>ortoreksija</li></ul><p>Lečenje uključuje terapiju i podršku stručnjaka.</p>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako sprečiti grickanje između obroka?',
                'answer' => 'Planirajte međuobroke, pijte više vode, jedite zdrave užine, ostanite aktivni i pratite navike koje izazivaju grickanje.',
                'html_answer' => '<p>Prevencija grickanja:</p><ul><li>zdravi međuobroci</li><li>dovoljno vode</li><li>fizička aktivnost</li><li>analiza uzroka (stres, dosada)</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako zadržati optimalnu težinu?',
                'answer' => 'Održavajte uravnoteženu ishranu, redovno vežbajte, spavajte dovoljno, i izbegavajte ekstremne dijete.',
                'html_answer' => '<p>Saveti:</p><ul><li>zdrava ishrana</li><li>fizička aktivnost</li><li>dovoljan san</li><li>izbegavati ekstremne dijete</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako stvoriti zdrav odnos prema hrani?',
                'answer' => 'Fokusirajte se na nutritivnu vrednost hrane, odbacite ideju “dobrih” i “loših” namirnica, slušajte telo i budite strpljivi.',
                'html_answer' => '<p>Koraci ka zdravom odnosu:</p><ul><li>fokus na nutritivnu vrednost</li><li>nema zabrana</li><li>slušajte telo</li><li>ne brojite samo kalorije</li><li>budite strpljivi</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako naučiti decu o pravilnoj ishrani?',
                'answer' => 'Budite primer, uključite ih u pripremu hrane, pričajte o zdravoj hrani, i učinite obroke zanimljivim i edukativnim.',
                'html_answer' => '<p>Saveti za roditelje:</p><ul><li>budite dobar primer</li><li>uključite decu u kuvanje</li><li>objasnite važnost zdrave hrane</li><li>učinite obroke zabavnim</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'question' => 'Kako inspirisati i podržati druge pri usvajanju zdravih navika?',
                'answer' => 'Predložite zajedničke aktivnosti, postavite ciljeve zajedno, podelite uspehe, i budite strpljivi i podržavajući.',
                'html_answer' => '<p>Kako pomoći drugima:</p><ul><li>zajedničke zdrave aktivnosti</li><li>postavljanje ciljeva</li><li>motivacija i pohvale</li><li>strpljenje i razumevanje</li></ul>',
                'category' => 'kat1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];

        DB::table('faqs')->insert($faqs);
    }
}
