<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\FoodstuffController;
use App\Http\Controllers\OnBoardingQuestionController;
use App\Http\Controllers\OnBoardingQuestionOptionController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\UserController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');
Route::post('/add-option',[OnBoardingQuestionOptionController::class,'store'])->name('api.add-option');
Route::post('/delete-option',[OnBoardingQuestionOptionController::class, 'deleteOption'])->name('api.delete-option');
Route::post('/add-question',[OnBoardingQuestionController::class, 'addQuestion'])->name('api.add-question');
Route::post('/delete-question',[OnBoardingQuestionController::class, 'deleteQuestion'])->name('api.delete-question');
Route::put('/update-question/{id}', [OnBoardingQuestionController::class, 'updateQuestion'])->name('api.update-question');
Route::put('/update-option/{id}', [OnBoardingQuestionOptionController::class, 'updateOption'])->name('api.update-option');
Route::get('/create-user',[UserController::class, 'createUser'])->name('api.create-user');
Route::get('/onboarding/questions/{questionSetIndex}/{language}', [OnBoardingQuestionController::class, 'getOnboardingQuestions'])->name('api.onboarding-questions');
Route::post('/onboarding/answers/_calculate', [OnBoardingQuestionController::class, 'saveFirstAnswers'])->name('api.calculate-answers');
Route::post('/onboarding/answers/_finalize', [OnBoardingQuestionController::class, 'saveSecondAnswers'])->name('api.finalize-answers');
Route::get('/firebase-test', [AuthController::class, 'firebaseLogin'])->name('firebase-test');
Route::post('/users/assign-firebase-uid', [UserController::class, 'assignFirebaseUid'])->name('assign-firebase-uid');
Route::get('/users/get-user-recipes', [UserController::class, 'getRecipesByUserIdAndWeek'])->name('get-user-recipes');
Route::get('/users/get-user-recipe', [UserController::class, 'getRecipeByUserIdAndRecipeId'])->name('get-user-recipe');
Route::get('/get-recipes', [RecipeController::class, 'getRecipes'])->name('get-recipes');
Route::post('/update-recipe-status', [RecipeController::class, 'updateRecipeStatus'])->name('update-recipe-status');
Route::post('/update-user-water', [UserController::class, 'updateUserWater'])->name('update-user-water');
Route::get('/faqs', [RecipeController::class, 'getFaqs'])->name('get-faqs');
Route::get('/faq/{id}', [RecipeController::class, 'getFaq'])->name('get-faq');
Route::get('/faqs/categories', [RecipeController::class, 'getFaqCategories'])->name('get-faqs-categories');
Route::get('/users/get-user-calories', [UserController::class, 'getUserCalories'])->name('get-user-calories');
Route::post('/users/add-scope', [UserController::class, 'addScope'])->name('add-scope');
Route::get('/users/get-scopes', [UserController::class, 'getUserScopes'])->name('get-user-scopes');
Route::post('/users/add-photo', [UserController::class, 'addPhoto'])->name('add-photo');
Route::get('/users/get-photos', [UserController::class, 'getUserPhotos'])->name('get-user-photos');
Route::get('/users/get-user-photo-first', [UserController::class, 'getUserPhotoFirst'])->name('get-user-photo-first');
Route::get('/users/get-user-photo-last', [UserController::class, 'getUserPhotoLast'])->name('get-user-photo-last');
Route::get('/users/get-user-scope-first', [UserController::class, 'getUserScopeFirst'])->name('get-user-scope-first');
Route::get('/users/get-user-scope-last', [UserController::class, 'getUserScopeLast'])->name('get-user-scope-last');
Route::post('/update-recipe-bookmark-status', [RecipeController::class, 'updateRecipeBookmarkStatus'])->name('update-recipe-status');
Route::get('/users/get-water', [UserController::class, 'getUserWater'])->name('get-user-water');
Route::get('/user', [UserController::class, 'getUser'])->name('get-user');
Route::post('/users/apple-sign-in-callback', [UserController::class, 'appleSignInCallback'])->name('apple-sign-in-callback');
Route::post('/users/add-user-weight', [UserController::class, 'addUserWeight'])->name('add-user-weight');
Route::get('/users/get-user-weights', [UserController::class, 'getUserWeights'])->name('get-user-weight');
Route::post('/users/delete-user-weight', [UserController::class, 'deleteUserWeights'])->name('delete-user-weights');
Route::post('/users/delete-user-photo', [UserController::class, 'deleteUserPhoto'])->name('delete-user-photo');
Route::get('/recipes/get-shop-foodstuffs', [UserController::class, 'getShopFoodstuffs'])->name('get-shop-foodstuffs');
Route::get('/recipes/get-recipe-shop-foodstuffs', [UserController::class, 'getRecipeShopFoodstuffs'])->name('get-recipe-shop-foodstuffs');
Route::get('/recipes/filter-recipes', [RecipeController::class, 'filterRecipes'])->name('get-recipes');
Route::post('/recipes/update-shop-foodstuffs', [UserController::class, 'updateShopFoodstuffs'])->name('update-shop-foodstuffs');
Route::post('/users/delete-user-scope', [UserController::class, 'deleteUserScope'])->name('delete-user-scope');
Route::post('/users/update-user', [UserController::class, 'updateUser'])->name('update-user');
Route::get('/recipes/get-foodstuffs-by-category', [RecipeController::class, 'getFoodstuffsByCategory'])->name('get-foodstuffs-by-category');
Route::get('/foodstuff/foodstuff-categories', [FoodstuffController::class, 'foodstuffCategories'])->name('get-foodstuff-categories');
Route::get('/users/change-user-recipe', [UserController::class, 'changeUserRecipe'])->name('change-user-recipe');
Route::post('/users/generate-new-meal-plan', [UserController::class, 'generateNewMealPlan'])->name('generate-new-meal-plan');
Route::post('/users/update-meal-calendar', [UserController::class, 'updateMealCalendar'])->name('update-meal-calendar');
Route::post('/users/repeat-meals', [UserController::class, 'repeatMeals'])->name('repeat-meals');
Route::get('/user/get-onboarding-2', [OnBoardingQuestionController::class, 'getOnboardingQuestion2'])->name('get-onboarding-2');
Route::post('/generate-new-plan', [RecipeController::class, 'generateNewPlan'])->name('generate-new-plan');
Route::get('/users/get-subscribers', [UserController::class, 'getSubscribers'])->name('get-subscribers');
Route::post('/users/add-subscriber', [UserController::class, 'addSubscriber'])->name('add-subscriber');
Route::post('/users/update-notification-token', [UserController::class, 'updateNotificationToken'])->name('update-notification-token');
Route::post('/users/update-notification-status', [UserController::class, 'updateNotificationStatus'])->name('update-notification-status');
Route::post('/notification-test', [UserController::class, 'sendNotificationTest'])->name('send-notification-test');
Route::get('/users/get-user-recipe-alternatives', [UserController::class, 'getUserRecipeAlternatives'])->name('get-user-recipe-alternatives');
Route::post('/users/change-user-recipe-alternative', [UserController::class, 'changeUserRecipeAlternative'])->name('change-user-recipe-alternative');
Route::post('/validate-subscription', [UserController::class, 'validateSubscription']);
